#include "ms5611.h"
#include "mmc5983ma.h"
#include "icm42688.h"
#include "neom9n.h"
#include "ekf_interface.h"
#include <math.h>

// Declare external hardware handles generated by STM32CubeMX
extern SPI_HandleTypeDef hspi1; 
extern SPI_HandleTypeDef hspi2;
extern NEOM9N_HandleTypeDef gps_device; 

void SensorMain_Run(void) {
    ICM42688_RawData imu;
    MMC5983MA_RawData mag;
    Ms5611_RawData baro;
    NEOM9N_GPSData gps;

    HAL_StatusTypeDef imu_status;
    HAL_StatusTypeDef mag_status;
    HAL_StatusTypeDef baro_status;
    bool gps_valid = false;
    float yaw_degrees = 0.0f;
    float altitude_meters = 0.0f;

    /* * 1. Read IMU (ICM42688) via SPI 
     */
    imu_status = ICM42688_ReadIMUData(
        &hspi1,
        ICM_CS_GPIO_Port,
        ICM_CS_Pin,
        &imu
    );

    /* * 2. Read Magnetometer (MMC5983MA) via SPI
     * Note: Write "Take Measurement" bit prior to calling this if not auto-sampling
     */
    /* Trigger a single measurement, then poll status until complete. */
    mag_status = MMC5983MA_WriteRegister(
        &hspi2,
        MAG_CS_GPIO_Port,
        MAG_CS_Pin,
        MMC5983MA_REG_CONTROL_0,
        MMC5983MA_CTRL0_TM_M
    );

    if (mag_status == HAL_OK) {
        uint32_t start = HAL_GetTick();
        uint8_t status_reg = 0;
        /* poll for measurement-done, timeout after 10 ms */
        do {
            if (MMC5983MA_ReadRegister(&hspi2, MAG_CS_GPIO_Port, MAG_CS_Pin, MMC5983MA_REG_STATUS, &status_reg) != HAL_OK) {
                status_reg = 0;
                break;
            }
            if ((status_reg & MMC5983MA_STATUS_MEAS_M_DONE) != 0) break;
        } while ((HAL_GetTick() - start) < 10);

        mag_status = MMC5983MA_ReadMagneticField(&hspi2, MAG_CS_GPIO_Port, MAG_CS_Pin, &mag);
    }

    /* * 3. Read Barometer (MS5611) via SPI
     * Fixed: Converted from hi2c1 to SPI parameters.
     * Note: Call MS5611_SendCommand(..., MS5611_CMD_CONVERT_D1_OSR4096) 
     * and wait before reading ADC.
     */
    uint32_t raw_adc = 0;

    /* Read PROM (calibration) and then perform compensated conversions.
       Ms5611_ReadCompensated() performs the conversion + ADC reads.
       We still read the raw ADC value once to preserve previous API usage. */
    baro_status = Ms5611_ReadData(&hspi1, BARO_CS_GPIO_Port, BARO_CS_Pin, &baro);
    if (baro_status == HAL_OK) {
        /* perform full compensated read (pressure & temperature) */
        if (Ms5611_ReadCompensated(&hspi1, BARO_CS_GPIO_Port, BARO_CS_Pin, &baro) == HAL_OK) {
            /* also obtain the raw ADC for compatibility with existing EKF call */
            /* Trigger pressure conversion and read raw ADC (D1) */
            if (Ms5611_SendCommand(&hspi1, BARO_CS_GPIO_Port, BARO_CS_Pin, MS5611_CMD_CONVERT_D1_OSR4096) == HAL_OK) {
                HAL_Delay(MS5611_CONVERSION_DELAY_MS);
                Ms5611_ReadADC(&hspi1, BARO_CS_GPIO_Port, BARO_CS_Pin, &raw_adc);
            }
        } else {
            baro_status = HAL_ERROR;
        }
    }

    /* * 4. Read GPS (NEO-M9N) from background UART parsing
     */
    gps = gps_device.data;
    gps_valid = gps.fix_valid;

    /* * 5. State Prediction & EKF Updates 
     */
    if (imu_status == HAL_OK) {
        process_imu_and_predict(&imu);
        update_ekf_attitude(&imu);
    }

    if (baro_status == HAL_OK) {
        update_ekf_barometer(raw_adc, &baro);

        /* compute altitude (meters) from pressure using barometric formula
           baro.pressure is centi-mbar (mbar * 100) per Ms5611_ReadCompensated() */
        float pressure_mbar = (float)baro.pressure / 100.0f;
        const float sea_level_mbar = 1013.25f;
        /* altitude (m) = 44330 * (1 - (P/P0)^(1/5.255)) */
        altitude_meters = 44330.0f * (1.0f - powf(pressure_mbar / sea_level_mbar, 0.190294957f));
    }

    if (gps_valid) {
        update_ekf_gps(&gps);
    }

    if (mag_status == HAL_OK) {
        update_ekf_magnetometer(&mag);

        /* compute simple 2D heading (yaw) from magnetometer X/Y axes
           Note: this is not tilt-compensated; for accurate yaw with
           pitched/rolled vehicle, apply tilt compensation using IMU
           orientation (not implemented here). */
        float mx = (float)mag.mag_x;
        float my = (float)mag.mag_y;
        float heading = atan2f(my, mx); /* radians */
        yaw_degrees = heading * (180.0f / (float)M_PI);
        if (yaw_degrees < 0.0f) yaw_degrees += 360.0f;
    }

    /* At this point we have computed `yaw_degrees` and `altitude_meters`.
       You can feed them into higher-level state update functions or expose
       them via globals/getters as needed. For now, call the generic
       pose update function (preserves existing flow). */
    update_aircraft_pose();
}

/* Optional helpers (static) could be added if further reuse is desired. */